#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TicTacToeLab.Droid.Resource", IsApplication=true)]

namespace TicTacToeLab.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::TicTacToeLab.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::TicTacToeLab.Droid.Resource.String.Hello;
			global::Cirrious.MvvmCross.Plugins.ReflectionEx.Droid.Resource.String.ApplicationName = global::TicTacToeLab.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.ReflectionEx.Droid.Resource.String.Hello = global::TicTacToeLab.Droid.Resource.String.Hello;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::TicTacToeLab.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::TicTacToeLab.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::TicTacToeLab.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::TicTacToeLab.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::TicTacToeLab.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::TicTacToeLab.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::TicTacToeLab.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::TicTacToeLab.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::TicTacToeLab.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::TicTacToeLab.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::TicTacToeLab.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::TicTacToeLab.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::TicTacToeLab.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::TicTacToeLab.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::TicTacToeLab.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::TicTacToeLab.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::TicTacToeLab.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::TicTacToeLab.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::TicTacToeLab.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::TicTacToeLab.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::TicTacToeLab.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::TicTacToeLab.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::TicTacToeLab.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::TicTacToeLab.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::TicTacToeLab.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001d
			public const int MvxBind = 2130771997;
			
			// aapt resource value: 0x7f010021
			public const int MvxDropDownItemTemplate = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int MvxItemTemplate = 2130772000;
			
			// aapt resource value: 0x7f01001e
			public const int MvxLang = 2130771998;
			
			// aapt resource value: 0x7f010022
			public const int MvxSource = 2130772002;
			
			// aapt resource value: 0x7f01001f
			public const int MvxTemplate = 2130771999;
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int ahBarColor = 2130771988;
			
			// aapt resource value: 0x7f01001c
			public const int ahBarLength = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int ahBarWidth = 2130771995;
			
			// aapt resource value: 0x7f010019
			public const int ahCircleColor = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int ahDelayMillis = 2130771992;
			
			// aapt resource value: 0x7f01001a
			public const int ahRadius = 2130771994;
			
			// aapt resource value: 0x7f010015
			public const int ahRimColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int ahRimWidth = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int ahSpinSpeed = 2130771991;
			
			// aapt resource value: 0x7f010011
			public const int ahText = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int ahTextColor = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int ahTextSize = 2130771987;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int uiCompass = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiRotateGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiScrollGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiTiltGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomControls = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int useViewLifecycle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int zOrderOnTop = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int common_signin_btn_text_dark = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_signin_btn_text_light = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int green = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int red = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_signin_btn_icon_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_disabled_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_focus_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_normal_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_pressed_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_disabled_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_focus_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_normal_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_pressed_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_errorstatus = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_plusone_medium_off_client = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_plusone_small_off_client = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_standard_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_tall_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_successstatus = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int roundedbg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int roundedbgdark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int splash = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int Image = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int MvxBindingTagUnique = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int adView = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int hybrid = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int loadingImage = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int loadingProgressBar = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int loadingProgressWheel = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int normal = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int oButton = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int resumeButton = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int satellite = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int terrain = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int textViewStatus = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int xButton = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loading = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingimage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingprogress = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SplashScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int XOCell = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05001d
			public const int ApplicationName = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int Hello = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int app_name = 2131034142;
			
			// aapt resource value: 0x7f050015
			public const int auth_client_needs_enabling_title = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int auth_client_needs_installation_title = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int auth_client_needs_update_title = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int auth_client_play_services_err_notification_msg = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int auth_client_requested_by_msg = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int auth_client_using_bad_version_title = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_button = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_enable_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_text_phone = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_tablet = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_install_title = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_invalid_account_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_invalid_account_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_network_error_text = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_network_error_title = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_unknown_issue = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unsupported_date_text = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_unsupported_text = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_unsupported_title = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_update_button = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_text = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_update_title = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int common_signin_button_text = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int common_signin_button_text_long = 2131034131;
			
			// aapt resource value: 0x7f05001b
			public const int library_name = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int location_client_powered_by_google = 2131034138;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] MapAttrs = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] MvxBinding = new int[]
			{
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771999};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130772002};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130772000,
					2130772001};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
